emerge --depclean: 'str' has no attribute 'soname' (bug 657420)
Convert str to Atom, in order to avoid an AttributeError in the
DbapiProvidesIndex.match method. Also, add comment explaining the
reason for _unicode(atom) usage here, since it's not obvious.

Bug: https://bugs.gentoo.org/657420